[workspace]
resolver = "2"

members = [
    "os-infrastructure",
    "system-network-interface",
    "os-network-admin",
]

[workspace.package]
version = "0.1.0"
authors = ["PointSav Digital Systems AG"]
edition = "2024"

# Global Optimization for Sovereign Artifacts
[profile.dev]
panic = "abort"

[profile.release]
opt-level = 3
lto = true
panic = "abort"
strip = true
