[package]
name = "system-substrate"
version = "0.1.0"
edition = "2021"

[dependencies]
# Corrected features for the x86_64 Sovereign Substrate
sel4 = { git = "https://github.com/seL4/rust-sel4", default-features = false }

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
